# Generated by Django 5.0.1 on 2024-02-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn10', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('thumbnail', models.URLField()),
                ('description', models.TextField()),
                ('published_year', models.IntegerField()),
                ('average_rating', models.FloatField()),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
