# Generated by Django 5.0.1 on 2024-02-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_book_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(),
        ),
    ]
