# Generated by Django 5.0.1 on 2024-03-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
