# Generated by Django 5.0.1 on 2024-03-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_alter_book_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Authorname',
            new_name='Author_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='isbn10',
            new_name='isbn_no',
        ),
        migrations.RenameField(
            model_name='myrating',
            old_name='ratingno',
            new_name='rating_no',
        ),
    ]
