# Generated by Django 5.0.1 on 2024-02-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(),
        ),
    ]
