# Generated by Django 5.0.1 on 2024-02-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_book_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
    ]
