# Generated by Django 5.0.1 on 2024-02-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_remove_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now_add=True, default='2024-02-02'),
            preserve_default=False,
        ),
    ]
