# Generated by Django 5.0.1 on 2024-02-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0016_alter_book_created_at_alter_book_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
