# Generated by Django 5.0.1 on 2024-02-02 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0019_remove_book_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
