# Generated by Django 5.0.1 on 2024-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0020_book_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
