# Generated by Django 5.0.1 on 2024-02-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0021_alter_book_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added_date',
        ),
    ]
