# Generated by Django 5.0.1 on 2024-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0022_remove_book_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default='2024-02-02'),
        ),
    ]
