# Generated by Django 5.0.1 on 2024-02-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0023_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
