# Generated by Django 5.0.1 on 2024-02-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0025_rename_publication_date_book_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_date',
            new_name='publication_date',
        ),
    ]
