# Generated by Django 5.0.1 on 2024-02-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0026_rename_added_date_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
