# Generated by Django 5.0.1 on 2024-02-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0027_book_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
