# Generated by Django 5.0.1 on 2024-02-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0029_alter_book_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_amount', models.FloatField()),
            ],
        ),
    ]
