# Generated by Django 5.0.1 on 2024-02-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0033_delete_order_alter_myrating_book_alter_myrating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrating',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='myrating',
            old_name='rating',
            new_name='ratingno',
        ),
        migrations.RenameField(
            model_name='myrating',
            old_name='user',
            new_name='user_id',
        ),
    ]
