# Generated by Django 5.0.1 on 2024-02-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0034_rename_book_myrating_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrating',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='myrating',
            old_name='user_id',
            new_name='user',
        ),
    ]
