# Generated by Django 5.0.1 on 2024-02-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0035_rename_book_id_myrating_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('Author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Author', models.TextField()),
            ],
        ),
    ]
