# Generated by Django 5.0.1 on 2024-02-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0036_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author',
            new_name='Authorname',
        ),
    ]
