# Generated by Django 5.0.1 on 2024-02-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0037_rename_author_author_authorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_name', models.CharField(max_length=255)),
            ],
        ),
    ]
