# Generated by Django 5.0.1 on 2024-02-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0038_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn10', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('thumbnail', models.URLField(blank=True)),
                ('upload', models.ImageField(blank=True, upload_to='uploads/')),
                ('description', models.TextField()),
                ('published_year', models.IntegerField(null=True)),
                ('average_rating', models.FloatField(null=True)),
                ('num_pages', models.IntegerField(null=True)),
                ('ratings_count', models.IntegerField(null=True)),
                ('price', models.FloatField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Book.category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='Book.author')),
            ],
        ),
    ]
