# Generated by Django 5.0.1 on 2024-02-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0040_boook_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='Book.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Book.category'),
        ),
        migrations.DeleteModel(
            name='Boook',
        ),
    ]
