# Generated by Django 5.0.1 on 2024-02-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0041_alter_book_authors_alter_book_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
