# Generated by Django 5.0.1 on 2024-02-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('cod', 'Cash on Delivery')], default='cod', max_length=50),
        ),
    ]
