# Generated by Django 5.0.1 on 2024-02-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
